### ISSUE TITLE
import plan

### ISSUE THREAD

**Issue by hasufell** [gentoo/libressl#100]
@blueness now that we are on git, I think we could start to mess around with this in the tree

Any big blockers yet? Should we just import it and start adding libressl support to packages as we go? Start in a separate branch?

The dummy openssl ebuild could remain here, so that people can still test libressl system-wide, until we have added the `libressl` USE flag everywhere.

**Comment by hasufell** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/log/?h=project%2Flibressl

I think there is really not much left. Even python doesn't require patching anymore, except slot `:3.3`. And ruby still requires patching. Everything else, like apache, nginx and so on seem to work.

**Comment by hasufell** [comment]
https://github.com/gentoo/libressl/wiki/Transition-plan

**Comment by hasufell** [comment]
test @gentoo/reviewers

**Comment by blueness** [comment]
What is the libressl branch of the main gentoo tree for?

**Comment by hasufell** [comment]
it was a test if development works better there... the test has failed
