### ISSUE TITLE
ssl, gnutls, what...

### ISSUE THREAD

**Issue by krosos** [gentoo/libressl#110]
Do we need to change useflags like in wine
  ssl? ( net-libs/gnutls:=[${MULTILIB_USEDEP}] )
to something other than ssl, maybe directl use "gnutls" in the IUSE, or am I thinking to complicated?

**Comment by EvaSDK** [comment]
SSL is for the "feature", not the lib, the specific USE flag is when there is multiple implementations supported by the package.

**Comment by krosos** [comment]
Okay, so only when the RDEPEND/DEPEND lists currently openssl as the package it needs to be tested. "wine" got me confused after filtering out untested ones with ssl / openssl flag.
Thanks

**Comment by hasufell** [comment]
the libressl USE flag is _only_ for switching the `libssl.so` and friends provider to `dev-libs-/libressl`. It is not a feature USE flag. It is completely disconnected from ssl, gnutls or even openssl flag (so sometimes, you really want USE="openssl libressl").
