### ISSUE TITLE
Got wierd blockage with openssl-999 and libressl-2.2.6

### ISSUE THREAD

**Issue by aleiphoenix** [gentoo/libressl#124]
```
Calculating dependencies... done!
[ebuild  N     ] dev-libs/openssl-9999::libressl  USE="zlib -bindist -kerberos -static-libs" ABI_X86="(64) -32 (-x32)" 0 KiB
[ebuild  N    ~]  dev-libs/libressl-2.2.6:0/35::gentoo  USE="asm -static-libs" ABI_X86="(64) -32 (-x32)" 0 KiB
[blocks B      ] dev-libs/openssl:0 ("dev-libs/openssl:0" is blocking dev-libs/libressl-2.2.6)

Total: 2 packages (2 new), Size of downloads: 0 KiB
Conflict: 1 block (1 unsatisfied)
```

Just synced gentoo portage, got libressl 2.2.6. When I tried to upgrade libressl, got this wierd blockage.

in `/usr/portage/dev-libs/libressl/libressl-2.2.6.ebuild`

```
RDEPEND="!dev-libs/openssl:0"
DEPEND="${RDEPEND}"
PDEPEND="app-misc/ca-certificates"
```

in `<this overlay>/dev-libs/openssl/openssl-9999.ebuild`

```
SLOT="0"

DEPEND=">=dev-libs/libressl-2.0.0[static-libs?,${MULTILIB_USEDEP}]"
RDEPEND="${DEPEND}
        app-misc/c_rehash"
```

I've checked `libressl-2.2.4.ebuild` from github.com/gentoo/gentoo [here](https://github.com/gentoo/gentoo/blob/0171d63fb6075caf0db45f1d26ff18556afb5ab5/dev-libs/libressl/libressl-2.2.4.ebuild#L18). It also has `RDEPEND="!dev-libs/openssl:0"` . But worked normally.

I made a overlaied version of libressl-2.2.6 and remove `RDEPEND="!dev-libs/openssl:0"`, the blockage seemed solved.

So is this some issue?

**Comment by blueness** [comment]
I've dropped the openssl ebuild from the overlay, so it may be that some other package is pulling in openssl.  I know this will cause blockers like this, but I'd like to get libressl support into the tree as soon as possible.

**Comment by aleiphoenix** [comment]
So it is supposed to use `ssl libressl` USE flags now?

**Comment by lluixhi** [comment]
Yes.

**Comment by blueness** [comment]
@aleiphoenix did you get past the blocking issue?

**Comment by blueness** [comment]
i'm pretty sure this is just an artifact of my deprecation of openssl-9999 on the overlay.  so for others, unmerge openssl-9999 and set USE="ssl libressl" system wide.  you may have to keyword some packages.
