### ISSUE TITLE
libressl-2.3.3 keywording

### ISSUE THREAD

**Issue by lluixhi** [gentoo/libressl#128]
According the the libressl website, libressl 2.3.3 is the latest stable version, but we still have it masked. Should we fix this?

**Comment by blueness** [comment]
its because of SSLv3 support is completely missing.  This is the correct direction but some packages will break.  I'd like to continue with 2.2 for a while.  If you like you can confirm what breaks with 2.3 and report.  Just unmask locally and recompile world.

**Comment by lluixhi** [comment]
I've actually had it unmasked for a while now.

There have not been that many build-time bugs, and the ones I did have I've been reporting.  

I have not yet checked if there are other bugs, but I figured they'd show up at link-time..

**Comment by blueness** [comment]
can you comment on this bug since it lead me to mask it

https://bugs.gentoo.org/show_bug.cgi?id=567554

**Comment by lluixhi** [comment]
On that bug, the only things not fixed upstream are the patches on qtcore and qtnetwork, which QT doesn't appear to be interested in fixing.

The other ones were fixed upstream, but some of them have yet to hit portage or be unmasked.

We actually can drop the patched ruby versions from this overlay because it appears that as of November 18, 2015 the 2.0,2.1,2.2,and 2.3 branches were patched to support a lack of SSLv3 in Open/LibreSSL. The latest versions of ruby in portage were all released on December 16, 2015.

**Comment by blueness** [comment]
we cannot keyword 2.2 stable, we have not gotten far enough through the migration.

the qtcore patches are not trivial.  if QT is not interested in fixing those bugs, then what?  will the QT team downstream be willing to carry those patches forward.  they may not.  so i'm not sure about proceeding this way.

**Comment by lluixhi** [comment]
That's true.

I agree, I don't think the QT team should be maintaining these patches. Either way, the last time something was reported, the QT project's stance was that they did not claim to support LibreSSL. I suppose we could open more bug reports and hope for the best?

**Comment by blueness** [comment]
what about QT on OpenBSD? we might be able to leverage some support if QT wants to continue to work on OpenBSD.  anyhow in the long run QT will have to drop SSLv3.  Its foobar and openssl will eventually drop it too.

**Comment by lluixhi** [comment]
QT already checks for OPENSSL_NO_SSL3_METHOD, so that doesn't need to be patched, luckily. OpenBSD appears to be patching a lot of qt5, and I don't see any open bugs on the qt bugtracker. Maybe they decided to just maintain their patches?

**Comment by blueness** [comment]
yep, sounds like something OpenBSD would do.   okay when this become critical i'll go begging our QT people :(

**Comment by lluixhi** [comment]
@blueness 
Yeah, it doesn't look like I'm going to be able to get this merged.
https://codereview.qt-project.org/#/c/154800

**Comment by blueness** [comment]
okay the original point of this issue was to get libress-2.3 unmasked.  both 2.3.x and 2.4.x are unmasked now.  this ill put pressure on maintainers to drop sslv3 support which is coming.
