### ISSUE TITLE
Verify/update php and fetchmail patches.

### ISSUE THREAD

**Issue by lluixhi** [gentoo/libressl#136]
Are these patches still relevant?
They haven't been updated in a while and no one has complained.

If they are still relevant they should be updated.

**Comment by blueness** [comment]
php is off the tree.

**Comment by blueness** [comment]
why wouldn't the fetchmail patch be relevant?  can you provide details.

**Comment by dorvan** [comment]
I see the same bug, but only on different USE sets, I've to try to reproduce problem with different USE set.
