### ISSUE TITLE
nodejs testsuite fails with the provided patch

### ISSUE THREAD

**Issue by Gottox** [gentoo/libressl#143]
I guess you are using my patchset from http://github.com/Gottox/node. (at least some comments in the patch lead me to that conclusion)

There where reasons, why it was only available for node-4.3 ;)

The following tests fail:

```
=== release test-tls-client-mindhsize ===                                      
Path: parallel/test-tls-client-mindhsize
Trace: WARNING: DH parameter is less than 2048 bits
    at Object.createSecureContext (_tls_common.js:105:15)
    at new Server (_tls_wrap.js:753:25)
    at Object.TLSSocket._init.ssl.onclienthello.exports.createServer (_tls_wrap.js:846:10)
    at test (/home/tox/src/node/test/parallel/test-tls-client-mindhsize.js:32:20)
    at testDHE1024 (/home/tox/src/node/test/parallel/test-tls-client-mindhsize.js:67:3)
    at Object.<anonymous> (/home/tox/src/node/test/parallel/test-tls-client-mindhsize.js:76:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: 2 == 1
    at process.<anonymous> (/home/tox/src/node/test/parallel/test-tls-client-mindhsize.js:91:10)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
Command: out/Release/node /home/tox/src/node/test/parallel/test-tls-client-mindhsize.js
=== release test-tls-cnnic-whitelist ===                         
Path: parallel/test-tls-cnnic-whitelist
Command: out/Release/node /home/tox/src/node/test/parallel/test-tls-cnnic-whitelist.js
--- CRASHED ---
=== release test-tls-ocsp-callback ===                                  
Path: parallel/test-tls-ocsp-callback
Command: out/Release/node /home/tox/src/node/test/parallel/test-tls-ocsp-callback.js
--- CRASHED ---
=== release test-tls-pfx-gh-5100-regr ===                       
Path: parallel/test-tls-pfx-gh-5100-regr
Command: out/Release/node /home/tox/src/node/test/parallel/test-tls-pfx-gh-5100-regr.js
--- CRASHED ---
[01:13|% 100|+ 1032|-   4]: Done                                               
```

Using gdb I found out that the crash is at TLSWrap::ClearOut():

```
read = SSL_read(ssl_, out, sizeof(out));
```

The out buffer is staticly allocated, so the real error is in the SSL context (ssl_)

**Comment by Gottox** [comment]
Furthermore it seems to happen in server mode (ssl_->handshake_func == ssl23_accept)

**Comment by blueness** [comment]
i'm not sure who ported it to other versions.  i'm happy to take a pull requrest even if it is just to remove what's broken.

**Comment by lluixhi** [comment]
@blueness it was my mistake. I modified Gottox' patch but didn't check whether all the tests passed until recently while I was attempting to clean it up to submit upstream to node.  

The assertion failure in minDHSize is because of the removal of the ephemeralKeyInfo pieces in _tls_wrap.js and I don't know of a way to reject keys less than a certain number of bits in LibreSSL, though it does provide a warning, so I believe it should exist.  

I guess we should double check what other SSL context handling changed between 4.3 and 5.x that's making it crash now.

**Comment by blueness** [comment]
@lluixhi no problem dude, see what you can do with it and we'll yank it if we have to

**Comment by Gottox** [comment]
If s/o got a fix, I'll happy include it into my fork too.

**Comment by blueness** [comment]
issue a pull request and we'll put it on the main overlay for everyone to enjoy
