### ISSUE TITLE
Cannot emerge layman, curl issue?

### ISSUE THREAD

**Issue by jmrtns** [gentoo/libressl#158]
I'll admit that I am new to gentoo and that this may just be a silly mistake on my part but I was going to try layman in a virtual machine but I cannot emerge layman and it seems to be a curl-7.49.0 issue

"
root@vmGentoo **emerge layman**

...

[blocks B      ] dev-libs/openssl:0 ("dev-libs/openssl:0" is blocking dev-libs/libressl-2.4.2)

Total: 22 packages (22 new), Size of downloads: 24,118 KiB
Conflict: 1 block (1 unsatisfied)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (dev-libs/libressl-2.4.2:0/39::gentoo, installed) pulled in by
    dev-libs/libressl:0= required by (dev-perl/Net-SSLeay-1.720.0-r1:0/0::gentoo, ebuild scheduled for merge)
    dev-libs/libressl:= required by (dev-vcs/git-2.7.3-r1:0/0::gentoo, ebuild scheduled for merge)

  **(dev-libs/openssl-1.0.2h-r2:0/0::gentoo, ebuild scheduled for merge)** pulled in by
    dev-libs/openssl:0=[static-libs?,abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (dev-libs/openssl:0=[abi_x86_64(-)]) required by **(net-misc/curl-7.49.0:0/0::gentoo, ebuild scheduled for merge)**
"

"
root@vmGentoo **emerge net-misc/curl**

Calculating dependencies... done!
[ebuild  N    #] dev-libs/openssl-1.0.2h-r2  USE="asm sslv3 tls-heartbeat zlib -bindist -gmp -kerberos -rfc3779 -sctp -sslv2 -static-libs {-test} -vanilla" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="(sse2)" 
[ebuild  N     ] net-misc/curl-7.49.0  USE="ipv6 ssl -adns -http2 -idn -kerberos -ldap -metalink -rtmp -samba -ssh -static-libs {-test} -threads" ABI_X86="(64) -32 (-x32)" CURL_SSL="openssl -axtls -gnutls (-libressl) -mbedtls -nss -polarssl (-winssl)" 
**[blocks B      ] dev-libs/openssl:0 ("dev-libs/openssl:0" is blocking dev-libs/libressl-2.4.2)**

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  **(dev-libs/openssl-1.0.2h-r2:0/0::gentoo, ebuild scheduled for merge)** pulled in by
    dev-libs/openssl:0=[static-libs?,abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (dev-libs/openssl:0=[abi_x86_64(-)]) required by **(net-misc/curl-7.49.0:0/0::gentoo, ebuild scheduled for merge)**

  (dev-libs/libressl-2.4.2:0/39::gentoo, installed) pulled in by
    dev-libs/libressl required by (net-misc/wget-1.18:0/0::gentoo, installed)
    dev-libs/libressl required by (net-misc/iputils-20151218:0/0::gentoo, installed)
    dev-libs/libressl:= required by (dev-lang/python-3.4.3-r7:3.4/3.4m::gentoo, installed)
    dev-libs/libressl:0/39= required by (dev-lang/python-3.4.3-r7:3.4/3.4m::gentoo, installed)
    dev-libs/libressl:0/39= required by (dev-lang/python-2.7.11-r2:2.7/2.7::gentoo, installed)
    dev-libs/libressl:= required by (dev-lang/python-2.7.11-r2:2.7/2.7::gentoo, installed)
    dev-libs/libressl required by (net-misc/openssh-7.2_p2-r1:0/0::gentoo, installed)
"

**Comment by csmk** [comment]
That's because the `libressl` USE flag for _curl_ is masked, as you can see in:
> CURL_SSL="openssl -axtls -gnutls **(-libressl)** -mbedtls -nss -polarssl (-winssl)" 

To unmask, create a file called `use.mask` in /etc/portage/profile and add:
> -curl_ssl_libressl

Then add `CURL_SSL="libressl"` in /etc/portage/make.conf

Cheers!

**Comment by jmrtns** [comment]
I had a feeling it was due to my Gentoo illiteracy. Perhaps a small note in the README.md could help others? In either case, thank you!

**Comment by archenroot** [comment]
+1
