### ISSUE TITLE
Email to different ebuild developers about dependency loop on dev-libs/openssl for libressl transition.

### ISSUE THREAD

**Issue by dorvan** [gentoo/libressl#171]
Good Day, 

Thanks guys for your work on gentoo ebuilds, 
You receive this email for a conflict problems on one of following ebuilds, maintained by you.

About latest ebuild version of: 
net-libs/openslp, 
net-misc/miniupnpd, 
sys-cluster/glusterfs, 
net-misc/vpnc,  

and in CC to the Developer of Project:LibreSSL

The ebuild and present on the official gentoo portage repo,
and continue to manifest a loop dependencies check about "dev-libs/openssl" 
without a function in according to 

https://github.com/gentoo/libressl/wiki/Transition-plan

so, in conflict with libressl migration, and libressl migration howto published here

https://wiki.gentoo.org/wiki/Project:LibreSSL

Thanks and Regards,

Ivan

**Comment by blueness** [comment]
I don't get how.  I need more information here.  also emailing devs will probably get ignored.

**Comment by dorvan** [comment]
Probably yes, probably not... Also you are present in email destinations. 
And it's in the libressl's project interest get some feedback from (not only desktop) users. 
Especially from long time gentoo's users who remember python structure migration hell, in gentoo base layout. 
Thanks for all, always, for the work made everyday on Gentoo, but
this message and email, MAY HELP (yes, or not) if ears of all interested people remain alerted and oriented in the right way; so on "libressl" project good, structured, fast migration, aligned to other major distributions family, yes, because gentoo it's not only a community who make a distribution, but a distro family, an os infrastructure, who permit to other projects and distributions to live. Long time migrations and dependency problems with official repo or official projects overlay cause waterfall problem on other projects derived from Gentoo. 
Remeber always this aspect.

So, is it problably you read and set a priority aspect, on various issues I've highlighted about libressl project impact?

As user, derived gentoo project developer, I hope yes, simply to enhance the value of the time spent to approach the libressl migration on gentoo, and fr everyone have developed and documented a migration procedure or howto, not more aligned to the today reality and situation of the project.

Thanks,
Ivan
