### ISSUE TITLE
Problematic ebuilds during libressl transition. 11-2016

### ISSUE THREAD

**Issue by dorvan** [gentoo/libressl#172]
net-libs/nghttp2 1.16.0
net-mail/dovecot 2.2.26.0
net-misc/openvswitch 2.5.0 - 2.6.0
net-libs/openslp 1.2.1-r3
net-misc/miniupnpd 2.0
sys-cluster/glusterfs 3.7.4
net-misc/vpnc 0.5.3_p550
sys-cluster/keepalived 1.2.23
net-libs/nodejs-7.0.0

**Comment by csmk** [comment]
What kind of problems?

The latest nghttp2 and dovecot is building and running fine with `libressl` USE flag.

The openslp already has `libressl` USE flag added in the unstable arch, although I've not tested it.

**Comment by dorvan** [comment]
If you build it as oneshot or direct, yes, when you Launch a emerge -uDN @world or more you have a loop suggestion to unmask openssl about that package, also reclaimed by other USE of the ebuild.

**Comment by blueness** [comment]
Okay this is not really a bug, but the fact that those versions of those packages don't have libressl support.  So, if those packages are the latest versions (usually the ~arch versions) *and* they don't have libressl support (ie the don't have libressl in the USE flags) then let me know and I'll add that.  But if they have libressl support in the latest versions, even if its ~arch, then I'll ask you do add that package to your  packages.accept_keywords and be patient until its eventually stabilized in the tree.

So can you go through those packages and tell me which ones don't have libressl in the lastest version.  The only exception being nodejs which is causing us issues.

**Comment by dorvan** [comment]
issue it's not always a bug.

**Comment by blueness** [comment]
not a bug = there's nothing for me to do.  the more of such non-bug issues it have me work through, the less time i have to work on bugs.
