### ISSUE TITLE
ignoring gentoo portage convention /etc/portage/package.* it's not considered directory, but only file on libressl repo. This cause errors

### ISSUE THREAD

**Issue by dorvan** [gentoo/libressl#174]
in this example
eix-update OUTPUT where /etc/portage/package.use owned by portage:portage is a directory.

OUTPUT:
Reading Portage settings...
Building database (/var/cache/eix/portage.eix)...
[0] "gentoo" /ports/portage/ (cache: metadata-md5-or-flat)
     Reading category 164|164 (100) Finished
[1] "libressl" /var/lib/layman/libressl (cache: parse|ebuild*#metadata-md5#metadata-flat#assign)
     Reading category   8|164 (  4): app-crypt...Permission denied: '/etc/portage/package.use'

portageq failed
     Reading category   8|164 (  4): app-crypt...
cannot properly execute /var/lib/layman/libressl/app-crypt/johntheripper/johntheripper-1.7.9-r10.ebuild
     Reading category   8|164 (  4): app-crypt...
cannot properly execute /var/lib/layman/libressl/app-crypt/qca/qca-2.1.1.ebuild

**Comment by blueness** [comment]
i wonder if this is a problem in eix.  so let's be clear here, this works with *other* overlays but not the libressl overlay?  if so, it may be prudent to open a bug on bugs.gentoo.org and assign it to the maintainer of eix because i don't think there's anything wrong with the libressl overlay per se and this bug might bite other overlays too.

**Comment by dorvan** [comment]
It's not a problem in eix, because i have not problems with other overlay like dotnet and zugaina, or gentoo overlay ..... before I post an issue here, first of all like the old netiquette say, rtfm, and a scientific method approach it's used. Consider this, reading issues I've opened. Thanks.

**Comment by blueness** [comment]
so what's different about the libressl overlay?

**Comment by fbarthelery** [comment]
@dorvan what are the rights on `/etc/portage/package.use` ? Make sure it can be read and explore by `portage`user. A simple fix is  `chmod 755 /etc/portage/package.use`

**Comment by dorvan** [comment]
@fbarthelery @blueness was a problem related to an automatic creation of resolv.conf on a build system, there is a 640 permission and probably on user change, in process (layman, portage) have no access to internet. fixed some months ago, sorry for delay to close it. solved forcing a 644 in /etc/resolv.conf
