### ISSUE TITLE
net-wireless/hostapd on official portage tree

### ISSUE THREAD

**Issue by dorvan** [gentoo/libressl#175]
Almost all USE (crda, wps, sqlite) of net-wireless/hostapd depends on same compilation section;
and cause this error:

fst_session.o ../src/fst/fst_ctrl_aux.o ../src/fst/fst_ctrl_iface.o -lrt   -lnl-3 -lnl-genl-3 -lnl-3 -lnl-genl-3 -lnl-route-3 -ldl -lcrypto -lm
x86_64-pc-linux-gnu-gcc -Wl,-O1,--sort-common,--as-needed,-z,relro  -o hostapd_cli hostapd_cli.o ../src/common/wpa_ctrl.o ../src/utils/os_unix.o ../src/common/cli.o ../src/utils/eloop.o ../src/utils/common.o ../src/utils/wpa_debug.o ../src/utils/edit_simple.o -lrt
../src/eap_server/eap_server_pwd.o: In function `eap_pwd_process':
eap_server_pwd.c:(.text+0x1652): undefined reference to `hash_nt_password_hash'
../src/crypto/crypto_openssl.o: In function `dh5_init':
crypto_openssl.c:(.text+0x1066): undefined reference to `DH_set0_pqg'
crypto_openssl.c:(.text+0x1094): undefined reference to `DH_get0_key'
../src/crypto/crypto_openssl.o: In function `dh5_init_fixed':
crypto_openssl.c:(.text+0x1223): undefined reference to `DH_set0_pqg'
crypto_openssl.c:(.text+0x1266): undefined reference to `DH_set0_key'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1063: hostapd] Error 1
 * ERROR: net-wireless/hostapd-2.6::gentoo failed (compile phase):
 *   emake failed

**Comment by blueness** [comment]
i'm confused here, net-wireless/hostapd doesn't have libressl support.  its neither in the overlay nor on the tree with libressl support.  how are you hitting the above?
