### ISSUE TITLE
dev-libs/libressl-2.5.1 includes new OpenSSL defines

### ISSUE THREAD

**Issue by lluixhi** [gentoo/libressl#188]
Specifically SSL_get_server_tmp_key

We need to review the patches that different patches have for LibreSSL support. qtnetwork, for instance could use a simpler patch.
NodeJS will now also pass more tests.

**Comment by lluixhi** [comment]
This is complicated in qtnetwork by the fact that normally qt checks for the presence of functions in libssl at runtime.. but SSLeay returns 0x20000000000L -- so the only thing that I can do is hard depend on a newer version of libressl, or ignore the fact we have the function. @blueness ?

**Comment by blueness** [comment]
why does the presence of a new function break stuff.  i don't know the issue well enough to advise your on this.

**Comment by lluixhi** [comment]
The way that they implemented these functions is incompatible with the method used by OpenSSL, so stuff breaks -- such as in dev-python/cryptography, and in dev-qt/qtnetwork (#190)

**Comment by blueness** [comment]
other distros must be encountering this issue

**Comment by lluixhi** [comment]
Voidlinux and Alpine Linux appear to be using the LibreSSL "stable" series (2.4.x), so they haven't hit it yet.
I'm not sure what other distros are using LibreSSL at this point.

**Comment by lluixhi** [comment]
Specifically, there is this issue in `dev-python/cryptography` because it appears that they added some definitions without actually making them usable:
https://github.com/pyca/cryptography/issues/3247
https://github.com/pyca/cryptography/issues/3378

And then there is this section in `<openssl/ssl.h>` which is kind of worrying:
```
/*
 * Preprocessor compatibility section.
 *
 * Historically, a number of APIs were implemented in OpenSSL as macros and
 * constants to 'ctrl' functions. To avoid breaking #ifdefs in consumers, this
 * section defines a number of legacy macros.
 *
 * Although using either the CTRL values or their wrapper macros in #ifdefs is
 * still supported, the CTRL values may not be passed to SSL_ctrl and
 * SSL_CTX_ctrl. Call the functions (previously wrapper macros) instead.
 */
#define SSL_CTRL_SET_CURVES doesnt_exist
#define SSL_CTRL_SET_CURVES_LIST doesnt_exist

#define SSL_CTX_set1_curves SSL_CTX_set1_groups
#define SSL_CTX_set1_curves_list SSL_CTX_set1_groups_list
#define SSL_set1_curves SSL_set1_groups
#define SSL_set1_curves_list SSL_set1_groups_list
```

SSL_CTX_set1_groups is a macro that is in OpenSSL 1.1.1 (not yet released) and it is defined as SSL_CTX_ctrl(SSL_CTX*, SSL_CTRL_SET_GROUPS, ...) while LibreSSL decided to implement it as a function..

I expect as LibreSSL starts adopting more new functions they may also be changed in odd ways.

**Comment by lluixhi** [comment]
Whoops, forgot to mention that this version also hid the majority of the state in `struct ssl_st`.

This breaks openconnect and tlsdate(#194), and possibly others.

**Comment by blueness** [comment]
we're moving to stabilize 2.6.4.  is this relevant?

**Comment by steils** [comment]
Obsolete long ago. Closing the issue.
