### ISSUE TITLE
dev-qt/qtnetwork-5.7.1 fails to build

### ISSUE THREAD

**Issue by Shamus397** [gentoo/libressl#190]
It seems that the bump from libressl-2.4.5 to 2.5.1 broke qtnetwork-5.7.1.

Looks like I can't attach the build.log, so here's a pastebin: https://paste.pound-python.org/show/o4x47cPZiBwTPkshmm9f/

**Comment by lluixhi** [comment]
The patch needs to be updated for 2.5.1, it appears.
LibreSSL implemented `SSL_CTRL_SET_CURVES` in an incompatible way..

**Comment by Shamus397** [comment]
As you said the qtnetwork patch worked. Couldn't you solve the issue with selective patching? In other words, if the USE flag is +libressl, add the patch but otherwise skip it?

**Comment by lluixhi** [comment]
OpenSSL should no longer be broken but I haven't tested it yet -- but yeah, that would work too.

**Comment by Alessandro-Barbieri** [comment]
Same error with version 5.6.2

**Comment by lluixhi** [comment]
I've only modified the qtnetwork-5.7.1 patch, so qtnetwork-5.6.1 and qtnetwork-5.6.2 still only build with earlier libressl versions -- I suppose I could backport the patch though.
