### ISSUE TITLE
Installing nodejs-6.9.4 hangs on non-PAX kernels

### ISSUE THREAD

**Issue by grepwood** [gentoo/libressl#196]
Hello,

I have 2 hosts, one with PAX, one without. On the host without a PAX kernel, the emerge procedure hangs on `src_install()`. Uncommenting `pax-mark -m "${ED}"usr/bin/node` did not work. Also, `emake install DESTDIR="${D}"` hangs the sandbox so badly that it's not possible `SIGKILL` any emerge process associated with installing NodeJS. Closing the terminal with the hanging process however does the trick.

**Comment by grepwood** [comment]
Emerging with ``FEATURES=-sandbox`` didn't work.

**Comment by blueness** [comment]
@grepwood i didn't respond earlier because i wasn't sure what was happening with hardened-sources --- i am the maintainer though.  unfortunately upstream has dropped support and so i'm going to be dropping support downstream.  this is very sad, but i don't have much choice.

**Comment by grepwood** [comment]
@blueness sucks for them. OpenSSL is not the way to go... In the end, I managed to fix this issue by building a binary package. Anyone interested, the package lives in https://1337matrixp.pl/gentoo/amd64_nodejs
