### ISSUE TITLE
create a profile

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/libressl#197]
I was wondering why not create a profile in which broken packages can be masked and all the other cool stuff made possible by a profile.

I can start doing it and PR.

**Comment by blueness** [comment]
why do we need a profile?  we're already profile heavy in gentoo so i'd like to avoid expanding them.  anyhow, what do you recommend go into such a profile besides USE=libressl?

**Comment by Alessandro-Barbieri** [comment]
Masking known packages/useflags with issues

**Comment by blueness** [comment]
yeah, that might work because then we can unmask USE=libressl globally.  okay give me what you're thinking and i'll give it a serious look

**Comment by steils** [comment]
This issue looks obsolete. I think we should close it. Feel free to reopen if you have a PR.
