### ISSUE TITLE
dummy ebuild references

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/libressl#199]
The wiki references the dummy ebuild, but is gone.

**Comment by blueness** [comment]
where is that?

**Comment by csmk** [comment]
@Alessandro-Barbieri, yes, it was removed in this commit: https://github.com/gentoo/libressl/commit/94d3c2438172fca931b237a592959ed49c2abd83

@blueness, [here](https://github.com/gentoo/libressl/wiki/Transition-plan).

**Comment by blueness** [comment]
thanks
