### ISSUE TITLE
net-misc/openssh fails to compile

### ISSUE THREAD

**Issue by hellekin** [gentoo/libressl#201]
Hello,

`=net-misc/openssh-7.5_p1-r1::libressl` fails with `Failed Patch: openssh-7.5_p1-libressl_arc4random.patch !`

- **build log**
  - http://sprunge.us/BWTG `/var/tmp/portage/net-misc/openssh-7.5_p1-r1/temp/build.log`
  - http://sprunge.us/XENM `/var/tmp/portage/net-misc/openssh-7.5_p1-r1/temp/openssh-7.5_p1-libressl_arc4random.patch.out`
- **system info**
  - http://sprunge.us/VdTE `emerge --info '=net-misc/openssh-7.5_p1-r1::libressl'`
  - http://sprunge.us/PMRX `emerge -pqv '=net-misc/openssh-7.5_p1-r1::libressl'`

**Comment by lluixhi** [comment]
This should be fixed now. USE="X509" rewrites a lot of SSH and i didn't realize it would clash.
