### ISSUE TITLE
dev-qt/qtnetwork-5.9.2 fails to install

### ISSUE THREAD

**Issue by Shamus397** [gentoo/libressl#210]
Is it even possible to patch it for LibreSSL anymore? :-/

**Comment by blueness** [comment]
I need more information.

**Comment by Shamus397** [comment]
Well, if you try to emerge qtnetwork-5.9.2, it tries to pull in openssl instead of using the installed libressl. So it needs patching to support libressl, just like 5.7.x did. I tried using the 5.7.x patches with 5.9.2, and it didn't work.

**Comment by csmk** [comment]
Are you sure the `libressl` USE flag was enabled? Could have been masked on your side.

> So it needs patching to support libressl, just like 5.7.x did.

No, it's running fine with the latest LibreSSL.

**Comment by Shamus397** [comment]
Just saw it was updated in the overlay. Sorry for the noise.

**Comment by Shamus397** [comment]
OK, seems that there is a real problem here, though I don't know what it could be. Build log is here: https://paste.pound-python.org/show/C96KMZAvi9a0sagoQ6Qi/

Note that on a different machine with openssl installed, qtnetwork-5.9.2 succeeded in building. Considering that the change in the ebuild to support libressl is so minimal, I am at a loss to explain why it succeeds there and fails here. Also of note is that there is no config.tests/unix directory in the 5.9.2 tarball.

**Comment by Shamus397** [comment]
Traced it down to a eclass issue. Again, sorry for the noise.
