### ISSUE TITLE
ffmpeg has option --disable-ssl

### ISSUE THREAD

**Issue by Kokokokoka** [gentoo/libressl#217]
Found out that youtube-dl is not working because ffmpeg -p has no https.
And When one tries to emerge ffmpeg it has --disable-openssl 
even with libressl use-flag, this looks wrong.
Manually added --enable-openssl to the ebuild and youtube-dl now works.

**Comment by lluixhi** [comment]
You need USE="libressl openssl" for ffmpeg at the moment, otherwise the libressl use flag does nothing -- that was what the maintainer was okay with back when the ebuild patch was in the tree.

**Comment by Kokokokoka** [comment]
Ok, could you explicitly state this anywhere?
It's not that obvious,
thank you for your attention.

**Comment by lluixhi** [comment]
I'll add `libressl? ( openssl )` to `REQUIRED_USE` to make it more explicit -- I don't think it can get merged into ::gentoo like that though.
