### ISSUE TITLE
dev-libs/libressl-2.7.0 implements OpenSSL-1.0.1 and 1.1.0 APIs

### ISSUE THREAD

**Issue by lluixhi** [gentoo/libressl#219]
```
 * Added support for many OpenSSL 1.0.2 and 1.1 APIs, based on
   observations of real-world usage in applications. These are
   implemented in parallel with existing OpenSSL 1.0.1 APIs - visibility
   changes have not been made to existing structs, allowing code written
   for older OpenSSL APIs to continue working.
```
Some patches are going to need revisiting.

**Comment by blueness** [comment]
its in the main tree now.  we'll see what breaks and fix.

**Comment by purejoy** [comment]
Failed to build python3.6.4 after updating to libressl 2.7 on a Gentoo box. It seems that some extra header files are required while building _ssl module in order to find the declarations of some types. 
https://forums.gentoo.org/viewtopic-t-1078748.html

**Comment by Chaneybenjamini** [comment]
This also breaks python-2.7.14-1 for me, and someone on the Gentoo Forums reported that this breaks curl.

https://forums.gentoo.org/viewtopic-t-1078748.html

**Comment by lluixhi** [comment]
Here's a brief list of packages on my system that don't build -- there are others which build but don't use the new APIs, but they aren't really a priority:
```
app-arch/libarchive
dev-libs/libevent
dev-db/sqlcipher
dev-lang/ruby
dev-lang/python
net-misc/curl
net-vpn/openconnect
net-misc/aria2
net-wireless/wpa_supplicant
dev-python/cryptography
sys-fs/cryptsetup
```

**Comment by blueness** [comment]
I'm wondering if I should mask 2.7.0.

**Comment by Chaneybenjamini** [comment]
Probably. It completely breaks several core packages. I’ve already masked it on my system.

**Comment by blueness** [comment]
maked.

**Comment by blueness** [comment]
@lluixhi I started a tracker for packages breaking with dev-libs/libressl-2.7.0

https://bugs.gentoo.org/651228

**Comment by blueness** [comment]
we can put any patches for packages to build against >=dev-libs/libressl-2.7.0 on the overlay.

**Comment by CaseOf** [comment]
i did add some patches on a previous pull request https://github.com/gentoo/libressl/pull/220

**Comment by blueness** [comment]
@CaseOf if there are more to do and you feel like it, please go ahead and i'll commit them

**Comment by steils** [comment]
Obsolete. LibreSSL 2.9.1 is in the tree now.
