### ISSUE TITLE
openldap Could not locate TLS/SSL package 

### ISSUE THREAD

**Issue by hybridln** [gentoo/libressl#239]
I have the above problem so configure phase failed...
Is there any way to solve this?

**Comment by hybridln** [comment]
Also libressl is not compatible with spotify and elisa

**Comment by austin987** [comment]
Please attach config.log when attempting to configure with libressl.

Spotify/Elisa should be filed as separate bugs.

**Comment by hybridln** [comment]
https://pastebin.com/6sekgkNu
ok i will post another theme 

ps also sudo could not onstall with libressl

**Comment by steils** [comment]
Obsolete.
net-nds/openldap from the main tree works fine.
