### ISSUE TITLE
dev-qt/qtnetwork-5.11.1 doesn't build - patch available

### ISSUE THREAD

**Issue by V10lator** [gentoo/libressl#241]
As the title says after https://github.com/gentoo/libressl/commit/2ef0df5e34bbffd815af1b7a2353d2b8546487b4 there's no way to build dev-qt/qtnetwork. :(

**Comment by V10lator** [comment]
Whoops, now I see the ones in portage are already patched. Sorry about that. Still no way to compile dev-qt/qtnetwork-5.11.1 through.

**Comment by V10lator** [comment]
For 5.11.1 a patch from the ennui overlay seems to work: https://data.gpo.zugaina.org/ennui/dev-qt/qtnetwork/files/qtnetwork-5.11.0_rc2-libressl.patch

Would be great to have a ebuild including it in here.

**Comment by Chiitoo** [comment]
I've not looked into this in a year or few, but at least in the past we didn't want to patch things up for this, but rather have it upstreamed if anything.  Not so sure about the current times.

Here's some history on the matter: https://bugs.gentoo.org/562050

**Comment by V10lator** [comment]
@Chiitoo Yesterday I was browsing some FreeBSD developer sites and there they said such patches won't be upstreamed as long as nobody wants to maintain them. The reason behind this is that QT devs fear libreSSL support could break OpenSSL in the future. Here some links to FreeBSD and/or QT discussions (I can't find everything I readed yesterday anymore) :
https://bugreports.qt.io/browse/QTBUG-46292
https://bugreports.qt.io/browse/QTBUG-68374
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228344
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211832#c5

So I guess we won't see upstream libreSSL support any time soon and our best bet is keeping patches downstream (just like FreeBSD does).

**Comment by Chiitoo** [comment]
Indeed, I remember reading some Qt (upstream) bugs about this too, years ago, and I doubt things have changed much with regards to this over there (and looking that latest(?) bug about this there, it seems not at all really).  :\

Not sure what @Pesa's current thoughts on this are, but I might guess they have not changed much (if at all) either.

**Comment by cslycord** [comment]
[qtnetwork-5.11.2-libressl.patch.txt](https://github.com/gentoo/libressl/files/2497665/qtnetwork-5.11.2-libressl.patch.txt)

Here's an identical patch just changed for 5.11.2. Haven't tested it further than getting it to compile just now.

**Comment by blueness** [comment]
can you please provide a pull request

**Comment by cslycord** [comment]
Done. Forked it, uploaded, and added a pull request.

Hope it helps

**Comment by blueness** [comment]
pushed.  let me know if it doesn't work for some reason.

**Comment by ian-moone** [comment]
> let me know if it doesn't work for some reason.

Digests are missing. 👉 https://travis-ci.org/gentoo/libressl/builds/444013244#L951

**Comment by blueness** [comment]
fixed
