### ISSUE TITLE
media-video/ffmpeg contradictory REQUIRED_USE

### ISSUE THREAD

**Issue by soleera** [gentoo/libressl#245]
As stated in the title, the requirement `libressl? ( openssl )` is contradictory and confusing. It also makes this package impossible to emerge if openssl has been masked in the profile without a manual override in package.use.mask

**Comment by blueness** [comment]
Do you have a fix?  I'm busy these days and pull requests are happily accepted!

**Comment by steils** [comment]
Obsolete...
