### ISSUE TITLE
qtnetwork-5.11.1 doesn't build

### ISSUE THREAD

**Issue by sklv** [gentoo/libressl#258]
Hi,

I have libressl 2.6.2 and trying to build qtnetwork-5.11.1 fails with the below. I tried to upload the log but it didn't work so here's a [link](https://paste.pound-python.org/show/qTpr4psKPF1i999Vn7hF). 
The recent patch is applied, but the build still fails. I tried building 5.11.2 but it fails with what looks like the same error to me [link](https://paste.pound-python.org/show/tv7SoBWSF5AWTxyv1uzK/). Happy to provide any additional info.
```
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W
-Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -D_REENTRANT -fPIC -DQT_NO_USING_NAMESPACE
-DQT_NO_FOREACH -DQT_USE_SYSTEM_PROXIES -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT
-DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISA
BLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -
I. -Ikernel -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.11.1 -I../../include/QtNetwork/5.11.1/Q
tNetwork -isystem /usr/include/qt5/QtCore/5.11.1 -isystem /usr/include/qt5/QtCore/5.11.1/QtCore -isystem /usr/include/qt5
 -isystem /usr/include/qt5/QtCore -I.moc -I../../mkspecs/linux-g++ -o .obj/qsslsocket_openssl_symbols.o ssl/qsslsocket_op
enssl_symbols.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W
-Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -D_REENTRANT -fPIC -DQT_NO_USING_NAMESPACE
-DQT_NO_FOREACH -DQT_USE_SYSTEM_PROXIES -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT
-DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISA
BLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -
I. -Ikernel -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.11.1 -I../../include/QtNetwork/5.11.1/Q
tNetwork -isystem /usr/include/qt5/QtCore/5.11.1 -isystem /usr/include/qt5/QtCore/5.11.1/QtCore -isystem /usr/include/qt5
 -isystem /usr/include/qt5/QtCore -I.moc -I../../mkspecs/linux-g++ -o .obj/qssldiffiehellmanparameters_openssl.o ssl/qssl
diffiehellmanparameters_openssl.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W
-Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -D_REENTRANT -fPIC -DQT_NO_USING_NAMESPACE
-DQT_NO_FOREACH -DQT_USE_SYSTEM_PROXIES -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT
-DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISA
BLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -
I. -Ikernel -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.11.1 -I../../include/QtNetwork/5.11.1/Q
tNetwork -isystem /usr/include/qt5/QtCore/5.11.1 -isystem /usr/include/qt5/QtCore/5.11.1/QtCore -isystem /usr/include/qt5
 -isystem /usr/include/qt5/QtCore -I.moc -I../../mkspecs/linux-g++ -o .obj/qsslcertificate_openssl.o ssl/qsslcertificate_
openssl.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W
-Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -D_REENTRANT -fPIC -DQT_NO_USING_NAMESPACE
-DQT_NO_FOREACH -DQT_USE_SYSTEM_PROXIES -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT
-DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISA
BLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -
I. -Ikernel -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.11.1 -I../../include/QtNetwork/5.11.1/Q
tNetwork -isystem /usr/include/qt5/QtCore/5.11.1 -isystem /usr/include/qt5/QtCore/5.11.1/QtCore -isystem /usr/include/qt5
 -isystem /usr/include/qt5/QtCore -I.moc -I../../mkspecs/linux-g++ -o .obj/qsslellipticcurve_openssl.o ssl/qsslellipticcu
rve_openssl.cpp
In file included from ssl/qsslsocket_openssl_symbols.cpp:58:0:
ssl/qsslsocket_openssl_symbols.cpp: In function ‘BIO* q_BIO_new(const BIO_METHOD*)’:
ssl/qsslsocket_openssl_symbols_p.h:185:39: error: invalid conversion from ‘const BIO_METHOD* {aka const bio_method_st*}’
to ‘BIO_METHOD* {aka bio_method_st*}’ [-fpermissive]
     ret q_##func(arg) { funcret func(a); }
                                       ^
ssl/qsslsocket_openssl_symbols.cpp:193:1: note: in expansion of macro ‘DEFINEFUNC’
 DEFINEFUNC(BIO *, BIO_new, const BIO_METHOD *a, a, return 0, return)
 ^~~~~~~~~~
In file included from /usr/include/openssl/evp.h:67:0,
                 from /usr/include/openssl/hmac.h:67,
                 from /usr/include/openssl/ssl.h:149,
                 from ../../include/QtNetwork/5.11.1/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl
_p.h:60,
                 from ../../include/QtNetwork/5.11.1/QtNetwork/private/qsslcontext_openssl_p.h:1,
                 from ssl/qsslsocket_p.h:62,
                 from ssl/qsslsocket_openssl_p.h:70,
                 from ssl/qsslsocket_openssl_symbols_p.h:72,
                 from ssl/qsslsocket_openssl_symbols.cpp:58:
/usr/include/openssl/bio.h:575:7: note:   initializing argument 1 of ‘BIO* BIO_new(BIO_METHOD*)’
 BIO * BIO_new(BIO_METHOD *type);
       ^~~~~~~
make: *** [Makefile:23420: .obj/qsslsocket_openssl_symbols.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by sklv** [comment]
I have been able to build 5.11.2 with a subset of the path, attached.

[qtnetwork-5.11.2-libressl.patch.txt](https://github.com/gentoo/libressl/files/2597029/qtnetwork-5.11.2-libressl.patch.txt)

**Comment by blueness** [comment]
can you please prepare a pull request

**Comment by Dr-Terrible** [comment]
> error: invalid conversion from ‘const BIO_METHOD* {aka const bio_method_st*}’
to ‘BIO_METHOD* {aka bio_method_st*}’

That means that the source code requires an OpenSSL 1.1.1 API/ABI compatible library; which in turn means using libressl 2.8+. That is why qtnetwork is not compiling properly with libressl 2.6 (there isn't a BIO helper library with `const` signature).

**Comment by mschilli87** [comment]
@Dr-Terrible 
> qtnetwork v5.11.1 compiles fine with libressl v2.8.2.

Thx!

 I can confirm that adding 

```
=dev-libs/libressl-2.8.2
```
 to `/etc/portage/package.unmask`,

```
<dev-libs/libressl-2.8.0
```

 to `/etc/portage/package.mask`, and 

```
=dev-libs/libressl-2.8.2 ~amd64
=dev-qt/qtcore-5.11.2-r1 ~amd64
=dev-qt/qtdbus-5.11.2 ~amd64
=dev-qt/qtnetwork-5.11.2 ~amd64
```

to `/ect/portage/package.keywords` enabled me to successfully run

```sh
sudo emerge -1 '=dev-qt/qtnetwork-5.11.2::libressl'`
```

(with `libressl` in `USE` via `/etc/portage/make.conf`).

**Comment by blueness** [comment]
if i unmask libressl-2.8.* what breaks?

**Comment by mschilli87** [comment]
@blueness 
> if i unmask libressl-2.8.* what breaks?

I didn't check in detail, but there are definitely ~a lot of~several packages in my system that fail to build with `dev-libs/libressl-2.8.2`. But nothing that would actually break the whole system.

**Comment by casasnovas** [comment]
As a workaround, I've created an `fpermissive.conf` file in `/etc/portage/env/` with:
```
CFLAGS="${CFLAGS} -fpermissive"
CXXFLAGS="${CXXFLAGS} -fpermissive"
```

And a `/etc/portage/package.env/qtnetwork` file with:

```
dev-qt/qtnetwork fpermissive.conf
```

Which allows me to use the stable `libressl` version and get `qtnetwork` to compile just fine.  Hope that helps.

**Comment by mschilli87** [comment]
I ended up copying the current ebuild from this repository to a local overlay replacing the patch in the `files` directory by the one linked by @sklv above which works like a charm with `dev-libs/libressl-2.6.*`.

**Comment by blueness** [comment]
@mschiff @sklv can you prepare that patch as a pull request and I'll apply it.

**Comment by mschilli87** [comment]
@blueness: I already went ahead a prepared it until I noticed that I'm not on my Gentoo machine so I don't have repoman etc. available right now. I can run it and push tomorrow though.

**Comment by blueness** [comment]
no rush, make sure you attribute authorship to the proper author.  gentoo has become very picky about that.  and its the right thing to do.

**Comment by sklv** [comment]
I've done a PR #260 .

**Comment by blueness** [comment]
we made some changes, please test again if you don't mind.

**Comment by prototype99** [comment]
my build failed because "OpenSSL >= 1.1 is required" i can see a slot is available for it, so i made a pull request for that: #278

**Comment by ian-moone** [comment]
> my build failed because "OpenSSL >= 1.1 is required" i can see a slot is available for it, so i made a pull request for that

Which doesn't make much sense fixing OpenSSL here, since `::libressl` users expect fixes for... LibreSSL. You should file a bug report in Gentoo's Bugzilla.

**Comment by mschilli87** [comment]
According to [the corresponding Gentoo bug](https://bugs.gentoo.org/562050#c84) a [new patch](https://bugs.gentoo.org/attachment.cgi?id=558324&action=diff) is needed '*to compile `dev-qt/qtnetwork-5.12.9999::qt` against `dev-libs/libressl-2.9.0`*'.

**Comment by prototype99** [comment]
> > my build failed because "OpenSSL >= 1.1 is required" i can see a slot is available for it, so i made a pull request for that
> 
> Fixing OpenSSL compatibility here doesn't make much sense, since `::libressl` users expect fixes for... LibreSSL. You should file a bug report in Gentoo's Bugzilla.

this was exclusively for the libressl version, the official gentoo version was fine for some reason

**Comment by blueness** [comment]
@prototype99 actually it does make sense because if we ever want this in the tree, we nee the ebuild to work with *both* openssl and libressl.  But it would be good to open a bug on bugs.gentoo.org for openssl.

**Comment by ian-moone** [comment]
> this was exclusively for the libressl version, the official gentoo version was fine for **some reason**

So your solution is to force `>=dev-libs/openssl-1.1.0`? This is easily solvable by using `has_version`, [similar](https://github.com/gentoo/libressl/blob/210de5e1885b4d11bbc6bc1297e4958393913ce7/dev-qt/qtnetwork/qtnetwork-5.11.3.ebuild#L54-L58) to how was done in `qtnetwork-5.11.3`.

**Comment by flappyports** [comment]
Both versions in this overlay are working.  Anyone else still having issues?

**Comment by prototype99** [comment]
builds fine for me

**Comment by sklv** [comment]
Builds fine for me too.
