### ISSUE TITLE
dev-perl/Net-SSLeay build still failing.

### ISSUE THREAD

**Issue by CaseOf** [gentoo/libressl#287]
Hello,
In commit [6386d944b91ebd35c337c88f2091cf8a731e7863](https://github.com/gentoo/libressl/commit/6386d944b91ebd35c337c88f2091cf8a731e7863), dev-perl/Net-SSLeay was removed because it is apparently fixed in ::gentoo, but in reality, it's not. ::gentoo package still fail to build with libressl-2.9.0. Could we bring it back?

**Comment by CaseOf** [comment]
The patch I was giving in this package is still fixing the issue. Attached below.





[Net-SSLeay-1.82-libressl.patch.txt](https://github.com/gentoo/libressl/files/2970902/Net-SSLeay-1.82-libressl.patch.txt)

**Comment by blueness** [comment]
do not attach a patch, please prepare a pull request.

**Comment by steils** [comment]
Hi @CaseOf. There is already a PR for dev-perl/Net-SSLeay, and I left a comment there https://github.com/gentoo/libressl/pull/286#issuecomment-468980716

The same question: why don't you want to bump the package version? 1.86_09 has already been released. Or backport the upstream patches for LibreSSL support if you really need the stable version?

**Comment by blueness** [comment]
i pushed that PR.  If there's still a problem reopen this issue.
