### ISSUE TITLE
Problem syncing force-pushed master branch

### ISSUE THREAD

**Issue by kressh** [gentoo/libressl#305]
Hello!

Just got error after `emerge --sync`:

```
>>> Syncing repository 'libressl' into '/var/db/repos/libressl'...
/usr/bin/git fetch origin

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@laptop.(none)')
!!! git merge error in /var/db/repos/libressl
```

```
/var/db/repos/libressl # git status
On branch master
Your branch and 'origin/master' have diverged,
and have 2 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```
I did hard reset to older revision, then git pull, all works fine now.

But it still looks like bad practice to `push --force` gentoo repo or at least master branch.

Thanks

UPD: And thanks for awesome project, btw. Now I have fresh nodejs and no more conflicts with openssl-1.1+

**Comment by steils** [comment]
Hi. Thanks for the report.
I believe nobody does `push --force` except the bot that synchronizes github with the main repository (https://gitweb.gentoo.org/repo/proj/libressl.git/). Apparently somebody commited to github, and then the bot overwrote those commits with conflicting changes from libressl.git from gentoo.org.
I asked other developers not to push to github, but to libressl.git on gentoo.org instead.

Also it would be better not to use this github as a repository, as we moved it to gentoo.org, this is only a mirror. I would suggest:
```
eselect repository remove libressl
eselect repository add libressl
```

**Comment by kressh** [comment]
Thanks for response!
Can't remember why I added this repo manually instead of eselect-repository. So you're right, this was my mistake all along.
