### ISSUE TITLE
[security] dev-qt/qtnetwork-5.14.2 dropped, please bump to 5.14.2-r1

### ISSUE THREAD

**Issue by jeandestouches** [gentoo/libressl#321]
New stable release, 5.14.2-r1

https://packages.gentoo.org/packages/dev-qt/qtnetwork

Thanks

**Comment by jeandestouches** [comment]
ping

**Comment by KingDuckZ** [comment]
any news about this?

**Comment by mschilli87** [comment]
@steils, @dg98, @aidanharris, @blueness, @maurerpe, @cslycord, @V10lator, @lluixhi, @gled-rs: Anyone? :wink:

**Comment by jeandestouches** [comment]
@KingDuckZ @mschilli87 I copied the ebuild to my localrepo meanwhile. I don't understand why there is not an answer after 20 days.

**Comment by mschilli87** [comment]
@jeandestouches: Would mind opening a PR? Though I guess it won't receive any response either. :disappointed:

**Comment by steils** [comment]
I'm very sorry for the delay. My bad.

**Comment by mschilli87** [comment]
Thank you @steils. :tada:
No need to apologize. Yes: We have been nagging. But only because we care. And no: You do not owe us anything. If you don't find the time, it's our problem. :wink: So far no one (incl. me) even bothered to send a PR.
So thank you again. :heart:

**Comment by jeandestouches** [comment]
@steils Thank you!
