### ISSUE TITLE
problem with tpm2-tss

### ISSUE THREAD

**Issue by KingDuckZ** [gentoo/libressl#323]
emerge --update is complaining about the following:

```
app-crypt/tpm2-tss-2.4.1::gentoo USE="fapi -doc -gcrypt -openssl -static-libs -test" ABI_X86="(64)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( gcrypt openssl ) fapi? ( openssl )
```

I'm not sure what fapi or gcrypt do, I'll try changing those to sidestep the issue but would it be possible to have an ebuild of this that supports libressl?

**Comment by KingDuckZ** [comment]
This is currently a blocker for me, can someone offer some help please?

**Comment by et-8** [comment]
Sorry, not much help, but according the upstream issues libressl support doesn´t seem possible at the moment.
I am not involved in the libressl project  or tpm2-tss, maybe someone are working on the issue.
There is a discussion about getting rid of gcrypt.
Check out the upstream github issues:
https://github.com/tpm2-software/tpm2-tss/issues?q=Libressl

**Comment by KingDuckZ** [comment]
Thank you for your reply et-8. So is there a workaround at the moment?

**Comment by et-8** [comment]
So the gcrypt was removed 2 days ago:
https://github.com/tpm2-software/tpm2-tss/pull/1781

You should try remake the ebuild for libressl, following the "Migration to the Gentoo Repository - Direction for developers" guide on the [Gentoo wiki](https://wiki.gentoo.org/wiki/Project:LibreSSL).

Perhaps @alonbl can add the libressl option to this package now.
https://github.com/tpm2-software/tpm2-tss/issues/1235

**Comment by steils** [comment]
Thanks for the issue report.
I tried to build and run tests for the library. The USE flag is not the issue here. The library itself needs patching to work correctly.
I'll try to take care of it, but I'm not sure when.
Would be great if you create a bug on Gentoo bugzilla for this (and CC me there), because this is about a package in the main tree, not in the overlay. So I'm closing this issue.

**Comment by Titaniumtown** [comment]
I hope this gets fixed! I would love to use fwupd.
