### ISSUE TITLE
Update Qtnetwork to 5.15.1

### ISSUE THREAD

**Issue by MFHKiwi** [gentoo/libressl#326]
The LibreSSL-patched variant of Qtnetwork 5.15.1 is not yet available. Please fix this.

**Comment by steils** [comment]
It was fixed in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=14e199855f1089b896ca32482a5beb35521fa320

Please report such bugs to https://bugs.gentoo.org/ in the future, as LibreSSL should be supported by dev-qt/qtnetwork in the main repository.
