### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by anthonypants** [gentoo/libressl#329]
Now that LibreSSL is officially discontinued, and there's bound to be more people looking for instructions on how to keep using LibreSSL, maybe it'd be a good idea to put a more robust set of instructions here, or in the Gentoo wiki?

As far as I can tell, it's:
1) `emerge app-eselect/eselect-repository`
2) `eselect repository enable libressl`
3) `emaint sync -r libressl`
4) Add "-libressl" (and probably "-curl_ssl_libressl" as well) to `/etc/portage/profile/use.mask`
5) Add "dev-libs/libressl" to `/etc/portage/package.unmask`

**Comment by CaseOf** [comment]
Since libressl is not on main tree and that the USE flag no longer exists, enabling the overlay is enough to switch to libressl.

**Comment by orbea** [comment]
How is this supposed to work?

Now emerge wants to install the `dev-libs/openssl::gentoo` even when I have the dummy package from the libressl overlay, if I mask it I get errors like this:
```
!!! All ebuilds that could satisfy "dev-libs/openssl:0=[sslv3=,static-libs?,abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_s390_32(-)?,abi_s390_64(-)?]" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-libs/openssl-1.1.1k::gentoo (masked by: package.mask)
- dev-libs/openssl-1.0.2u::gentoo (masked by: package.mask)

(dependency required by "net-misc/curl-7.76.1::gentoo" [ebuild])
(dependency required by "dev-util/cmake-3.20.2::gentoo" [installed])
(dependency required by "sys-devel/llvm-11.1.0::gentoo" [installed])
(dependency required by "media-libs/mesa-9999::gentoo" [installed])
(dependency required by "x11-libs/cairo-1.16.0-r4::gentoo[opengl]" [installed])
(dependency required by "x11-libs/pango-1.42.4-r2::gentoo" [installed])
(dependency required by "x11-themes/gtk-engines-murrine-0.98.2-r1::gentoo" [installed])
(dependency required by "x11-themes/murrine-themes-0.98.0-r1::gentoo" [installed])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

**Comment by CaseOf** [comment]
Ah it wants the use sslv3?... I did not notice that in my tests. Can you tell me what needs that exactly?
If I have to add ghosts USE flags on dummy package, here we go....

**Comment by orbea** [comment]
The problem is in curl, I reverted the changes in curl for now and that got me farther.

**Comment by CaseOf** [comment]
Weird, curl did not made that to me...

**Comment by orbea** [comment]
I'm not sure why you can't reproduce it, but changing this line in `curl-7.76.1.ebuild` is enough to workaround the issue.
```
dev-libs/openssl:0=[sslv3=,static-libs?,${MULTILIB_USEDEP}]
````
To:
```
dev-libs/openssl:0=[static-libs?,${MULTILIB_USEDEP}]
```

**Comment by CaseOf** [comment]
Try to rebuild libressl and openssl from the overlay with `emerge --oneshot dev-libs/libressl::libressl dev-libs/openssl::libressl`

**Comment by orbea** [comment]
I did that, but it did not make a different for curl.
