### ISSUE TITLE
luasec 0.5 compile error

### ISSUE THREAD

**Issue by VanNostrand** [gentoo/libressl#38]
```
ssl.c: In function 'meth_compression':
ssl.c:404:3: error: unknown type name 'COMP_METHOD'
   const COMP_METHOD *comp;
   ^
<builtin>: recipe for target 'ssl.o' failed
```
the file is here: https://github.com/brunoos/luasec/blob/master/src/ssl.c

**Comment by hasufell** [comment]
did you report upstream?

**Comment by VanNostrand** [comment]
yes, I reported it. It seems they just need to include openssl/comp.h for libressl. (https://github.com/brunoos/luasec/issues/29)

**Comment by daurnimator** [comment]
Is that the correct fix? Does comp.h need to be included explicity now (when it didn't before?)

**Comment by hasufell** [comment]
any1 wants to set up a PR?
