### ISSUE TITLE
LibreSSL 3.5.0 causes build issues with various packages

### ISSUE THREAD

**Issue by mikejzx** [gentoo/libressl#382]
The bump to LibreSSL 3.5.0 has caused many packages to fail to build.  A few I've noticed personally include dev-perl/Net-SSLeay, dev-python/m2crypto (and hence net-wireless/crda), dev-qt/qtnetwork, and libevent (can be fixed by building without ssl USE flag, but this isn't really ideal).  

The patch files for these packages (and likely others) will need to be updated if support for these packages is desired.  Hence it's probably a good idea for most people using this overlay to hold LibreSSL at version 3.4.2 (or older) until the patch files get updated to work with the new 3.5.0.

Just from a brief look at build logs of these packages in particular, it seems that many of the compile-time errors are due to LibreSSL's structs now being written in an 'opaque' style (which is meant to be more compatible with OpenSSL, which does this already).

From the [release notes](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.0-relnotes.txt):
> - Most structs that were previously defined in the following headers
      are now opaque as they are in OpenSSL 1.1:
      bio.h, bn.h, comp.h, dh.h, dsa.h, evp.h, hmac.h, ocsp.h, rsa.h,
      x509.h, x509v3.h, x509_vfy.h

**Comment by CaseOf** [comment]
How could we set a mask in this configuration?
Maybe is it better to do nothing for now, and later drop dev-
python/m2crypto from the overlay?

**Comment by orbea** [comment]
In the case of packages that can be dropped for newer libressl while are still needed for older libressl perhaps they should be left alone where the user can mask them locally until the newer libressl is stabilized?

**Comment by orbea** [comment]
Make sure there are no implicit function declaration warnings, that was what was the issue last time. I haven't had time to update my gentoo lately, but maybe I will be able to join in on the fun soon. :)

**Comment by orbea** [comment]
`net-dns/bind-tools` was magically fixed by the `9.16.27` update in the gentoo repo.

https://gitweb.gentoo.org/repo/gentoo.git/commit/net-dns/bind-tools?id=7b918ba18b54e673b3b58f6dab03cb3c81f8148b

@thesamesam Thanks!

**Comment by orbea** [comment]
`net-misc/vpn` can be fixed by removing a forgotten (?) libressl patch in the gentoo repo.

https://github.com/gentoo/gentoo/pull/24623

**Comment by orbea** [comment]
@mikejzx Most of the issue should be resolved now?

**Comment by mikejzx** [comment]
> @mikejzx Most of the issue should be resolved now?

Yeah I've had no issues at all on my system recently, so I guess basically all the essential packages are compatible now :smiley:
