### ISSUE TITLE
>=dev-lang/python-3.10.8_p3 fails to build under LibreSSL 3.5.3

### ISSUE THREAD

**Issue by mikejzx** [gentoo/libressl#473]
```
/var/tmp/portage/dev-lang/python-3.11.0_p2/work/Python-3.11.0/Modules/_ssl.c: In function 'get_security_level':
/var/tmp/portage/dev-lang/python-3.11.0_p2/work/Python-3.11.0/Modules/_ssl.c:3590:28: error: implicit declaration of function 'SSL_CTX_get_security_level'; did you mean 'get_security_level'? [-Werror=implicit-function-declaration]
 3590 |     return PyLong_FromLong(SSL_CTX_get_security_level(self->ctx));
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            get_security_level
```

SSL_CTX_get_security_level was introduced only in LibreSSL 3.6.0.  From the [release notes](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.0-relnotes.txt):
>- The security level API (SSL_{,CTX}_{get,set}_security_level()) is
>     now available. Callbacks and ex_data are not supported. Sane
>     software will not be using this.

I haven't seen any patches for this online.  A simple solution is to just upgrade to LibreSSL 3.6.0.

For those that need 3.5.3 for whatever reason (e.g. in my case, I currently have a strange slot conflict when attempting to merge 3.6.0), I've written a patch that simply excludes the security_level code when building with any version below LibreSSL 3.6.0.  See #474

**Comment by orbea** [comment]
I think this is only needed for 3.11? I can't reproduce the build failure with libressl-3.5.3 and python-3.10.8_p3 on my end.

**Comment by botovq** [comment]
I would suggest that you neuter security level things like we did in OpenBSD by stubbing out the call in Python >= 3.10 with LibreSSL < 3.6 (with proper feature gating, of course). 
https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/lang/python/3.10/patches/Attic/patch-Modules__ssl_c?annotate=1.4
This is not a lie - LibreSSL's defaults have roughly corresponded to security level 1 for a long time.

Regarding the first hunk: beware of `@SECLEVEL=` annotations in cipher strings. Those can generate subtle runtime failures.

**Comment by mikejzx** [comment]
> I think this is only needed for 3.11? I can't reproduce the build failure with libressl-3.5.3 and python-3.10.8_p3 on my end.

Yeah you're right, my bad.  3.11 seems to be where the build failures start.  I kind of assumed that 3.10 would be broken too as this feature was merged into the 3.10 branch ([see](https://bugs.python.org/issue41195)).

I've just pushed a commit to only apply the patch to >=python-3.11.

**Comment by orbea** [comment]
> I would suggest that you neuter security level things like we did in OpenBSD by stubbing out the call in Python >= 3.10 with LibreSSL < 3.6 (with proper feature gating, of course).

I believe we already have this for python-3.10.

https://github.com/gentoo/libressl/blob/7e33a975e6ac0d67aae91c24d689eec6f3b4e9ac/dev-lang/python/files/python-3.10.3-libressl.patch

I suppose the `Modules/_ssl.c` fix could be rebased for 3.11?

**Comment by mikejzx** [comment]
> I would suggest that you neuter security level things like we did in OpenBSD by stubbing out the call in Python >= 3.10 with LibreSSL < 3.6 (with proper feature gating, of course). https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/lang/python/3.10/patches/Attic/patch-Modules__ssl_c?annotate=1.4 This is not a lie - LibreSSL's defaults have roughly corresponded to security level 1 for a long time.
> 
> Regarding the first hunk: beware of `@SECLEVEL=` annotations in cipher strings. Those can generate subtle runtime failures.

I just realised that we are actually already using the patch you linked for 3.10.8 (in python-3.10.3-libressl.patch).  This also explains why @orbea's build of 3.10.8 was succeeding, because the stub function was defined.

Presumably we can apply a similar patch to Python 3.11, but modify it so that the security level stuff is only neutered if LibreSSL is < 3.6.0.

As for the @SECLEVEL annotations, should these be removed when building with LibreSSL >= 3.6.0 ?

**Comment by botovq** [comment]
> I believe we already have this for python-3.10.

Ah, yes, indeed. I expect that this patch won't work with LibreSSL 3.6 since it exposes `SSL_CTX_get_security_level()` from libssl, so you'll need `#ifdef`. At least I had to remove that patch from the OpenBSD port when I added that API.

> I suppose the Modules/_ssl.c fix could be rebased for 3.11?

Yes, that should be straightforward. The diff between 3.10 and 3.11 is nearly trivial.

**Comment by botovq** [comment]
> As for the @SECLEVEL annotations, should these be removed when building with LibreSSL >= 3.6.0 ?

No, that is no longer necessary. libssl can parse that with LibreSSL 3.6 and later.

**Comment by mikejzx** [comment]
@botovq Thank you for the help.

I've written a new patch in #476 which should clean things up a little.

**Comment by botovq** [comment]
This patch looks good to me.

**Comment by orbea** [comment]
@mikejzx Thanks for the fix!
