### ISSUE TITLE
Add ruby 3.2

### ISSUE THREAD

**Issue by stefan11111** [gentoo/libressl#535]
Ruby 3.2 has been out for quite some time.
Any plans to add it to this overlay?

**Comment by orbea** [comment]
Are there any issues that need to be fixed? Last I tested 3.2 worked with without any changes, did I miss something?

**Comment by stefan11111** [comment]
Are there any plans to add python 3.12 to this overlay?
This one doesn't work as-is from ::gentoo

**Comment by orbea** [comment]
Currently there are only stable python versions here, but is there some pressing need for newer python versions? Its just its a lot of work to keep up with how much Gentoo changes the ebuilds.
