### ISSUE TITLE
Patches for 0.7.2

### ISSUE THREAD

**Issue by Sp1l** [gentoo/libressl#54]
Check https://github.com/Sp1l/ports/tree/master/security/py-cryptography where I generated a working patch-set for 0.7.2
1. Upgrades the port from 0.5.4 to 0.7.2
2. Removes EGD (Perl Entropy Gathering Daemon) support. This hasn't been needed on FreeBSD since FreeBSD 4.2
3. Disable compression conditionally using OPENSSL_NO_COMP
4. Check features, not version for x509_vfy
Based on the patches here and an issue on the py-cryptography GH

**Comment by hasufell** [comment]
yep
