### ISSUE TITLE
net-misc/openssh arc4random implicit function declaration

### ISSUE THREAD

**Issue by s0me0ne-coder** [gentoo/libressl#549]
seems to be fixed with libressl-3.8.2
[build.log](https://github.com/gentoo/libressl/files/14391896/build.log)

**Comment by orbea** [comment]
What libressl version are you reproducing this with?

It builds with libressl-3.7.3 for me.

**Comment by s0me0ne-coder** [comment]
it didn't for me with 3.7.3 but i was on llvm musl

**Comment by orbea** [comment]
Should be fixed in libressl-3.7.3-r1, thanks for the report!

**Comment by s0me0ne-coder** [comment]
you are welcome, i was getting tired of working around libressl issues over and over also could you bump python aswell

**Comment by orbea** [comment]
> also could you bump python aswell

Done.

There is only one person working on this repo most of the time so I only update packages when I run into them or have time to go through the repo for outdated packages. Please submit issues and / or pull requests if I am being slow in updating something.
