### ISSUE TITLE
Update to 2.1.4

### ISSUE THREAD

**Issue by Sp1l** [gentoo/libressl#66]
LibreSSL 2.1.4 tarball just landed on ftp.openbsd.org.
Please update ebuilds and take care of shlib version bump to 32

**Comment by hasufell** [comment]
> and take care of shlib version bump to 32

You mean the subslot?

**Comment by Sp1l** [comment]
Just seeked to inform you... Haven't been a Gentoo user for years...
libcrypto and libssl went from .30 to .32
