### ISSUE TITLE
openssh-6.8_p1 might need a patch? 

### ISSUE THREAD

**Issue by joecool1029** [gentoo/libressl#72]
Getting a build failure with the new openssh-6.8_p1 for the last 3 libressl versions.  

    ./libssh.a(cipher.o):cipher.c:function cipher_reset_multithreaded: error: undefined reference to 'evp_aes_ctr_mt'

If I drop out the ssl useflag, it will build.  But then I can't use sshkey authentication.  Nobody else on the web reported this yet so I've been hesitant to file a new bug on B.G.O.

**Comment by lluixhi** [comment]
I remember seeing a bug open for this issue on bugs.gentoo.org, but the issue disappeared.

**Comment by joecool1029** [comment]
I'm gonna guess it was RESOLUTION WONTFIX.  Will do search for it.

**Comment by joecool1029** [comment]
Here it is https://bugs.gentoo.org/show_bug.cgi?id=543736

**Comment by joecool1029** [comment]
Dammit, just ran another emerge --sync and it's fixed now.  Sorry for bugging you guys -_-
