### ISSUE TITLE
List of outdated packages

### ISSUE THREAD

**Issue by lluixhi** [gentoo/libressl#81]
We should update these:

www-servers/apache
app-admin/apache-tools (doesn't require patch)
dev-db/mysql
dev-lang/php
mail-filter/spamassassin
net-mail/dovecot

**Comment by joecool1029** [comment]
dev-libs/libressl can now be added to this list. 

2.1.7 and 2.2.0 were released today.

**Comment by lluixhi** [comment]
I actually just updated libressl this morning.  See #89

**Comment by joecool1029** [comment]
whoops sorry, my bad.  Forgot to check the pull requests.
