### ISSUE TITLE
Ruby 2.0 patch to compile with musl

### ISSUE THREAD

**Issue by amon-ra** [gentoo/libressl#91]
Hello default ruby 2.0 does not compile using musl libc. 
The ebuild is dev-lang/ruby/ruby-2.0.0_p645.ebuild, please add the following patch:

```
diff -Nuar ruby-2.0.0-p353.orig/io.c ruby-2.0.0-p353/io.c
--- ruby-2.0.0-p353.orig/io.c   2013-10-04 17:30:50.000000000 +0000
+++ ruby-2.0.0-p353/io.c        2014-02-23 13:22:06.038406133 +0000
@@ -19,6 +19,7 @@
 #include "id.h"
 #include <ctype.h>
 #include <errno.h>
+#include <asm/ioctl.h>
 #include "ruby_atomic.h"
 
 #define free(x) xfree(x)


```

**Comment by blueness** [comment]
Why is this patch coming to libressl.  Its on the musl overlay.  If you're using musl + libressl you can just add both repos.  I haven't check recently but in the early libressl overlay days, i made sure it worked on both musl and uclibc.

So I'm going to close this, but feel free to reopen it if you have good reasons why this needs to be in the libressl overlay too.

**Comment by amon-ra** [comment]
Sorry for my bad explanations.
I am installing the libressl under musl toolchain but the problem is that if I install the ruby that comes in the musl overlay fails for lack of your patches, and if I install this ruby fails for lack of musl patch.

I reported the bug to you because I think the patch of musl is simpler to apply.
