### ISSUE TITLE
dev-python/pypy request

### ISSUE THREAD

**Issue by lzsaver** [gentoo/libressl#95]
What about to add PyPy?

Currently, it does not support LibreSSL:
https://bitbucket.org/pypy/pypy/pull-request/233/fix-translation-for-libressl-and-fix-ssl

But it seems that it works well on OpenBSD (which uses LibreSSL by default):
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/lang/pypy/patches/

**Comment by hasufell** [comment]
pypy takes too long to build for me to work on this, especially because it only support `-j1`. Have fun ;)

**Comment by hasufell** [comment]
https://bitbucket.org/pypy/pypy/pull-requests/333/deal-with-platforms-without-rand_egd-take/diff

**Comment by hasufell** [comment]
pypy-2.6.1 seems to have the libressl fix, but it fails to build because of other crap, pypy3 PR is here https://github.com/gentoo/gentoo/pull/190

**Comment by hasufell** [comment]
That's something that'll happen in the tree automatically once 2.6.1 actually builds.
