### ISSUE TITLE
dev-libs/ffcall file collision

### ISSUE THREAD

**Issue by ghost** [gentoo/libressl#96]
dev-libs/ffcall-1.10-r5 and dev-libs/libressl-2.2.1 both want to install /usr/share/man/man3/callback.3.bz2

**Comment by blueness** [comment]
@lluixhi have you looked at this issue?  i'd like to make sure we don't have a file collision between two packages in the gentoo tree.

**Comment by steils** [comment]
There is no such file in dev-libs/libressl-2.8.3 and no collisions with ffcall. Let us close the issue.
